---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-rohan-com-v1-podfinder
  failurePolicy: Fail
  name: mpodfinder.kb.io
  rules:
  - apiGroups:
    - crd.rohan.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podfinders
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-rohan-com-v1-podfinder
  failurePolicy: Fail
  name: vpodfinder.kb.io
  rules:
  - apiGroups:
    - crd.rohan.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podfinders
  sideEffects: None
