apiVersion: crd.devops.toolbox/v1
kind: PodTracker
metadata:
  labels:
    app.kubernetes.io/name: podtracker
    app.kubernetes.io/instance: podtracker-sample
    app.kubernetes.io/part-of: crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crd
  name: podtracker-sample
spec:
  # TODO(user): Add fields here
